### ISSUE TITLE
How is this different from async-lsp crate?

### ISSUE THREAD

**Issue by Boscop** [ren-wei/async-lsp-client#1]
Hey, I'm wondering: How is this different from async-lsp crate? 🙂
https://crates.io/crates/async-lsp
https://github.com/oxalica/async-lsp/blob/main/examples/client_builder.rs

**Comment by ren-wei** [comment]
This crate is designed to be used to call another LSP server process in `tower-lsp`. It is the client with which it communicates. 

When I used tower-lsp, I didn't know about `async-lsp`, actually, I know about it now. I looked at the introduction to async-lsp and I agree with what it says about tower-lsp, which is also the issue I was experiencing.

I recommend using `async-lsp`.

**Comment by Boscop** [comment]
Thanks for your fast reply :)
